// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbvegikhzqxdxpldfdls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdidmVnaWtoenF4ZHhwbGRmZGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NTU4MDIsImV4cCI6MjA4NTMzMTgwMn0.cnLYEJCYFH4NjMyarYziqkG9mN99KfeSvSlsZRJ96sE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});